hymarch22/lovysplit/lovysimulation/urls.py
from django.urls import path
from . import views

app_name = "simulations"
urlpatterns = [
    path("", views.index, name="index"),
    # path("<str:name>", views.greet, name="greet"),
    path("<int:simulation_id>/edit/", views.edit, name="edit"),
    path("<int:simulation_id>", views.simulation, name="view"),
    path("add", views.add, name="add")
    # path("kimia", views.kimia, name="kimia"),
]

hymarch22/lovysplit/lovysplitdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lovysimulation/', include("lovysimulation.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
]

hymarch22/lovysplit/lovysimulation/models.py
from operator import mod
from re import M
from django.db import models


# Create your models here.
class Simulation(models.Model):
    folder_name = models.CharField(
        max_length=64,
        unique=True,
        blank=False,

    )
    excel_file_path = models.FileField(upload_to='excel_file_path')

    def __str__(self):
        return f"{self.id}: folder_name: {self.folder_name}, excel_file_path: {self.excel_file_path}"

class BackTraj(models.Model):
    pass

class Scenario(models.Model):
    scenario_name = models.CharField(
        max_length=64,
        unique=True,
        blank=False
    )

hymarch22/lovysplit/lovysimulation/forms.py
class NewSimulationForm(forms.ModelForm):
    class Meta:
        model = Simulation
        fields = ['id', 'folder_name', 'excel_file_path']

hymarch22/lovysplit/lovysimulation/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.urls import reverse
from .models import Simulation


class FirstNewSimulationForm(forms.Form):
    folder_name = forms.CharField(
        label="Name for the New Simulation",
        error_messages={'unique': u"This folder name is already used! Please change it."}
    )
    excel_file_path = forms.FileField(label="Excel file path for the Simulation")


class NewSimulationForm(forms.ModelForm):
    class Meta:
        model = Simulation
        fields = ['id', 'folder_name', 'excel_file_path']


def add(request):
    # Check if method is a POST
    if request.method == "POST":
        # Take in the data the user has submitted and save it as form
        form = NewSimulationForm(request.POST, request.FILES)

        # Check if form data is valid (server-side)
        if form.is_valid():

            # Isolate the task from the 'cleaned' version of form data
            folder_name = form.cleaned_data["folder_name"]
            excel_file_path = form.cleaned_data["excel_file_path"]

            # Add the new task to our list of tasks
            new_simulation = Simulation(
                folder_name=folder_name,
                excel_file_path=excel_file_path
            )
            new_simulation.save()

            # Redirect user to list of tasks
            return HttpResponseRedirect(reverse("simulations:index"))

        else:

            # If the form is invalid, re-render the page with existing information.
            return render(request, "lovysimulation/add.html", {
                "form": form
            })

    return render(request, "lovysimulation/add.html", {
        "form": NewSimulationForm()
    })


def edit(request, simulation_id=None):

    simulation = Simulation.objects.get(id=simulation_id)

    form = NewSimulationForm(request.POST or None, instance=simulation, files=request.FILES or None)

    if request.method == 'POST':

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("simulations:index"))
        else:
            return render(request, "lovysimulation/edit.html", {
                "form": form
            })

    return render(
        request, "lovysimulation/edit.html",
        {"form": form, "simulation": simulation}
    )


# Create your views here.
def index(request):
    return render(
        request,
        "lovysimulation/index.html",
        {"simulations": Simulation.objects.all()}
    )


def simulation(request, simulation_id):
    simulation = Simulation.objects.get(id=simulation_id)
    return render(request, "lovysimulation/simulation.html", {"simulation": simulation})


def kimia(request):
    return HttpResponse("Hello, Kimia!")


def greet(request, name):
    return render(
        request,
        "lovysimulation/greet.html",
        {
            "name": name.capitalize()
        }
    )

hymarch22/lovysplit/lovysimulation/templates/lovysimulation/add.html
{% extends "lovysimulation/layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row">
    <h1>Add a Simulation</h1>
</div>
<div class="row">
    <form action="{% url 'simulations:add' %}", method="post", enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-sm">
            {{ form.folder_name|as_crispy_field }}
        </div>
        <div class="col-sm">
            {{ form.excel_file_path|as_crispy_field }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
<div class="row">
    <a href="{% url 'simulations:index' %}">View Simulations</a>
</div>
{% endblock %}

hymarch22/lovysplit/lovysimulation/templates/lovysimulation/edit.html
{% extends "lovysimulation/layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row">
    <h1>Modify a Simulation</h1>
</div>
<div class="row">
    <form action="{% url 'simulations:edit' simulation.id %}", method="post", enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-sm">
            {{ form.folder_name|as_crispy_field }}
        </div>
        <div class="col-sm">
            {{ form.excel_file_path|as_crispy_field }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
<div class="row">
    <a href="{% url 'simulations:index' %}">View Simulations</a>
</div>
{% endblock %}

hymarch22/lovysplit/lovysimulation/templates/lovysimulation/greet.html
{% load static %}

<!DOCTYPE html>
    <head>
        <title> Greet someone </title>
        <link rel="stylesheet" href="{% static 'lovysimulation/styles.css' %}">
    </head>
    <body>
        <h1>Hello {{ name }}!! </h1>
    </body>
</html>

hymarch22/lovysplit/lovysimulation/templates/lovysimulation/index.html
{% extends "lovysimulation/layout.html" %}
{% load static %}

{% block body %}
    <h1>Simulations:</h1>
    <ul>
        {% for simulation in simulations %}
            <li>
                <a href="{% url 'simulations:view' simulation.id %}">
                    Simulation #{{ simulation.id}} at folder {{ simulation.folder_name }}  with file {{ simulation.excel_file_path }}
                </a>
                <a href="{% url 'simulations:edit' simulation.id %}">
                    Edit simulation {{ simulation.id}}
                </a>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'simulations:add' %}">Add a new Simulation</a>
{% endblock %}

hymarch22/lovysplit/lovysimulation/templates/lovysimulation/layout.html
<!DOCTYPE>
{% load bootstrap_tags %}
{% load crispy_forms_tags %}

<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>
            Simulations
        </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            {% block body%}
            {% endblock %}
        </div>
    </body>
</html>

hymarch22/lovysplit/lovysimulation/templates/lovysimulation/simulation.html
{% extends 'lovysimulation/layout.html' %}
{% load crispy_forms_tags %}

{% block body%}
    <h1> Simulation {{ simulation.id }} </h1>
    <ul>
        <li> Folder Name: {{ simulation.folder_name}}</li>
        <li> Excel File: {{ simulation.excel_file_path}}</li>
    </ul>
    <a href="{% url 'simulations:index' %}" class="btn-success">All Simulations</a>
{% endblock %}